[package]
name = "test-app"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
libc = "0.2"

memmap2 = "0.9"

[profile.release]
opt-level = 3	# Ensures the best performance for memory operations.
